### PR TITLE
Let projects be created via SPDX import without a project source.

### PR DESCRIPTION
**Pull request by matthewkmayer**

### CODE REVIEW

**Comment by struthj2** [comment]
overall looks good, my 2 cents (see the comment in jira issue too). Is if we want to use the cli to create projects plural from one spdx file. We should return a list of project structs from https://github.com/ion-channel/ionic/pull/460/files#diff-5bd6f147b98f488265f7a045024f3e1fcdb926a9b5c8ca6d85531eacbe5311c5R117. The method currently looks for a matching PackageName in an spdx file then will create one project. 

This could be done later, but I think the purpose of no source url required, was to allow us to create projects from an spdx file, rather than a single project.
Otherwise lgtm

**Review by struthj2 — APPROVED** [review]
see comment on PR, as is it looks good

**Comment by matthewkmayer** [comment]
Thanks, I will make those changes in this PR. 👍

**Comment by matthewkmayer** [comment]
Going to test this with ion-connect to ensure it works before asking for a merge.

**Comment by matthewkmayer** [comment]
Works from my testing. 👍

**Pull request merged**
