### PR TITLE
Sprinkle some logging around.

### PR DESCRIPTION
**Pull request by matthewkmayer**

### CODE REVIEW

**Comment by dan9186** [comment]
It might be easier to make these edits directly in the vendor directory copy of ionic so you don't have to go through a few rounds of PRs to add and remove later.

**Comment by matthewkmayer** [comment]
That's true.  My worry is mangling or otherwise changing something in the vendor dir and miss putting the good stuff back upstream.  Probably not an issue though.

**Comment by dan9186** [comment]
For concerns of that you could even skip merging it and do deploys to testing from your local machine.  Then nothing is checked in.  Either way, just a thought on how to give you faster turn around on these.

**Comment by matthewkmayer** [comment]
Found the bug, no need for this. 😄

**Pull request closed without merging**
